#!/usr/bin/env python3
"""
PHASE 4: Generate Full Text Using Federated Approach

Process: For each token, get distributions from 3 clients, average them, sample.
Result: Complete sentences generated by the "federated committee"
"""

import warnings, json, torch, os
from transformers import AutoTokenizer, AutoModelForCausalLM
from datetime import datetime

warnings.filterwarnings('ignore')
print("\nPHASE 4: Federated Text Generation\n" + "="*60)

MODEL = "meta-llama/Llama-3.1-8B-Instruct"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL)
    model = AutoModelForCausalLM.from_pretrained(MODEL).to(DEVICE)
    print("✓ Model loaded\n")
except Exception as e:
    print(f"❌ {e}")
    exit(1)

class FederatedDecoder:
    """Generate text by averaging token distributions from multiple clients"""
    
    def __init__(self, tokenizer, model, num_clients=3):
        self.tokenizer = tokenizer
        self.model = model
        self.num_clients = num_clients
    
    def generate(self, client_prompts, max_length=30):
        """Generate text by federated averaging"""
        # Start with client prompts
        inputs = [self.tokenizer(p, return_tensors="pt").to(DEVICE)["input_ids"] for p in client_prompts]
        
        output_tokens = []
        entropies = []
        
        for step in range(max_length):
            # Get distribution from each client
            dists = []
            for input_ids in inputs:
                with torch.no_grad():
                    out = self.model(input_ids)
                probs = torch.softmax(out.logits[0, -1, :], dim=-1)
                dists.append(probs)
            
            # Average distributions (federated approach)
            avg_dist = torch.mean(torch.stack(dists), dim=0)
            
            # Calculate uncertainty
            entropy = -torch.sum(avg_dist * torch.log(avg_dist + 1e-10)).item()
            entropies.append(entropy)
            
            # Pick next token (greedy)
            next_token_id = torch.argmax(avg_dist).unsqueeze(0).unsqueeze(0)
            next_token = self.tokenizer.decode([next_token_id.item()])
            next_prob = avg_dist[next_token_id.item()].item()
            
            output_tokens.append(next_token)
            print(f"  Step {step}: '{next_token}' ({next_prob:.1%}, uncertainty: {entropy:.2f})")
            
            # Continue with all clients
            inputs = [torch.cat([inp, next_token_id], dim=1) for inp in inputs]
        
        # Decode final output
        final_output = self.tokenizer.decode(torch.cat(inputs, dim=0)[0], skip_special_tokens=True)
        return {"tokens": output_tokens, "output": final_output, "entropies": entropies}

os.makedirs("results", exist_ok=True)
decoder = FederatedDecoder(tokenizer, model, num_clients=3)

scenarios = [
    {
        "name": "AI Definition",
        "prompts": [
            "I'm an ML engineer. Artificial intelligence is",
            "I'm a philosopher. Artificial intelligence is",
            "I'm a neuroscientist. Artificial intelligence is"
        ]
    },
    {
        "name": "Privacy in ML",
        "prompts": [
            "I work on privacy tech. Data privacy is important because",
            "I focus on compliance. Data privacy is important because",
            "I research differential privacy. Data privacy is important because"
        ]
    },
    {
        "name": "Token Decoding",
        "prompts": [
            "I'm a language model expert. Token decoding works by",
            "I study NLP. Token decoding works by",
            "I research transformers. Token decoding works by"
        ]
    }
]

all_results = {"timestamp": datetime.now().isoformat(), "scenarios": []}

for scenario in scenarios:
    print(f"\n{'-'*60}")
    print(f"Scenario: {scenario['name']}")
    print(f"{'-'*60}\n")
    
    result = decoder.generate(scenario["prompts"], max_length=30)
    
    avg_entropy = sum(result["entropies"]) / len(result["entropies"])
    print(f"\nGenerated: {result['output'][:100]}...")
    print(f"Avg uncertainty: {avg_entropy:.3f}\n")
    
    all_results["scenarios"].append({
        "name": scenario["name"],
        "output": result["output"],
        "tokens_generated": len(result["tokens"]),
        "avg_entropy": avg_entropy
    })

with open("results/phase_4_generations.json", "w") as f:
    json.dump(all_results, f)

print(f"{'='*60}\n✓ Saved to results/phase_4_generations.json")
print("\nKey insight: Federated generation produces coherent text!")
